### PR TITLE
feature(listeners, key) Show on double click or enter

### PR DESCRIPTION
**Pull request by maximmasterr**
When double click or enter on file open show

### CODE REVIEW

**Comment by coderaiser** [comment]
Thank you 🙂, that's an interesting idea. But what if file you suddenly clicked is too big (more than `1MB`), interface will be frozen for a while. What do you think about it? There is also thing that usual behavior is to open a program related to file extension, or just start a program.

**Comment by maximmasterr** [comment]
Create dialog window

**Comment by maximmasterr** [comment]
When file >1mb 
Or when has execute permission

**Comment by coderaiser** [comment]
Merged as https://github.com/coderaiser/cloudcmd/commit/e32e3ff47d4df3b7b5da29975d620b88165ea774.
Landed in [v12.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v12.0.0) 🎉.

**Pull request closed without merging**
