### PR TITLE
feature:cloudcmd:add context menu option to toggle file selection

### PR DESCRIPTION
**Pull request by hagaygo**
Adds option 3 of suggestions on https://github.com/coderaiser/cloudcmd/issues/418

I selected an existing icon that i thought is good enough for this context menu option.

Could not manage to add new icon so far, needs some pointers in adding new icon (added one in  the svg file and fontello.json , but it did not work)

- [x] `npm run fix:lint` is OK
- [x] `npm test` is OK

### CODE REVIEW

**Comment by coderaiser** [comment]
We need to choose an icon in [fontello.com](https://fontello.com/). Do you have any ideas?

**Comment by hagaygo** [comment]
I think something like check mark would fit.

One of these for example

**Comment by coderaiser** [comment]
Landed in [v18.2.0](https://github.com/coderaiser/cloudcmd/releases/tag/v18.2.0) 🎉

**Comment by hagaygo** [comment]
While the feature does work , i missed the fact that on mobile we don't have up/down buttons and when clicking on the "next file"  in the list it resets the selection, so its not possible yet to multi select files on mobile UI. (still the feature is really useful on desktop mode)

Also long press already shows the context menu.

I think the next change should be is to disable the existing selected files reset totally or only on mobile UI/view when the user click on a file on the list. 

Then the user will be able to select file 1 , long click to open context , toggle the selection , click on file 2 , toggle the selection and so on.

Other options is to add up/down buttons on the bottom on mobile view , which will allow the user to navigate on the list without triggering the selection reset, i think this is also nice to have regardless the missing feature above.

Let me know if i should try to implement those features or you have a better idea.

**Comment by coderaiser** [comment]
I don’t have a better idea, let’s try the simplest variant.

**Pull request merged**
