### PR TITLE
docs(help) improve English translation of HELP.md

### PR DESCRIPTION
**Pull request by twome**
This is mostly grammar and markup fixes (written by a native English speaker).

- [ ] commit message named according to [Contributing Guide](https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md "Contributting Guide")
- [x] `npm run codestyle` is OK
- [x] `npm test` is OK

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e3f09b4a49a31e7796baa5713944af96c7749e23
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e3f09b4a49a31e7796baa5713944af96c7749e23
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e3f09b4a49a31e7796baa5713944af96c7749e23
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by twome** [comment]
Ugh, I'm on library wifi, so I can't copy a local clone to properly squash these commits to fix the commit message issue. The builds *are* passing; the only issue is that the tests are picking up 'markdown' and 'npm' as typos for some reason.

**Comment by coderaiser** [comment]
Wow, so much changes! It looks much better, thank you  🙂.

**Pull request merged**
