### PR TITLE
feature(docker) add Dockerfile for arm based clients such as rpi

### PR DESCRIPTION
**Pull request by tea-mo903**
- [X] commit message named according to [Contributing Guide](https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md "Contributting Guide")
- [X] `npm run codestyle` is OK
- [X] `npm test` is OK

Image is based on the official [arm32v7/node image](https://hub.docker.com/r/arm32v7/node/)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62884094e96c18b33de03e7d7e754def5df7a2a9
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

Guidelines are available at https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by coderaiser** [comment]
Hi @tea-mo903, that's interesting idea :), could you please tell me why you set `python` version, and install it directly? It should be used only for building node.js itself from sources.

**Comment by tea-mo903** [comment]
Hi @coderaiser, its because the slim image of node does not consist of the python env. I tried also the fat node image, but it has then already a size of 1-2 gb, which is not applicable in an environment like a rpi. Btw I created a new PR (#268 ) which fits your commit policies. Was faster than ammending the old commit msg.

**Comment by coderaiser** [comment]
Why do you need `python` in `Cloud Commander` image :)?

**Comment by tea-mo903** [comment]
please refer to #268

**Pull request closed without merging**
