### PR TITLE
feature: cloudcmd: Add support for Progressive Web App

### PR DESCRIPTION
**Pull request by hagaygo**
More info about Progressive Web Apps on https://web.dev/explore/progressive-web-apps.

Tested on 2 android devices.

This PR adds a manifest.json file so mobile browser should allow/offer the user to use cloudcmd as PWA.

When hosted under valid HTTPS it provides better user experience and shows it as "regular app" (at least on my setups)

On non valid HTTPS/HTTP it shows the icon but includes a warning.

Example screenshot on valid https setup :

image

image

On non valid https/http :

image

### CODE REVIEW

**Comment by coderaiser** [comment]
Would be great to provide special image, since this looks bad at current resolution

**Comment by hagaygo** [comment]
Here it looks fine, but it is your call.
Feel free to change to what ever image you think is best (I think it has to be png, not sure)

**Comment by coderaiser** [comment]
please change to image I provided, but better to add a new image with size 256x256

**Comment by hagaygo** [comment]
Made the change.

**Comment by hagaygo** [comment]
Anything else needed before it gets merged ?

**Comment by coderaiser** [comment]
Yes, would be great to resize big image to 256x256 with something like https://imageresizer.com/, and create new file cloudcmd-256x256.png with mentioned size, and use it in manifest.

**Comment by hagaygo** [comment]
> Yes, would be great to resize big image to 256x256 with something like https://imageresizer.com/, and create new file cloudcmd-256x256.png with mentioned size, and use it in manifest.

Done.

**Comment by coderaiser** [comment]
Thank you!

**Comment by coderaiser** [comment]
Landed in [`v18.3.0`](https://github.com/coderaiser/cloudcmd/releases/tag/v18.3.0) 🎉

**Comment by hagaygo** [comment]
> Landed in [`v18.3.0`](https://github.com/coderaiser/cloudcmd/releases/tag/v18.3.0) 🎉

Any idea when it will be available as docker image on https://hub.docker.com/r/coderaiser/cloudcmd ?

**Comment by coderaiser** [comment]
Job failed, just restarted https://github.com/coderaiser/cloudcmd/actions/runs/11835324560

**Comment by hagaygo** [comment]
It seems there is a problem.

Chrome (test on 2 devices) not seem to pickup the manifest.json file and shows regular dialog.

I am running cloudcmd behind nginx so checked nginx log and found it that chrome requests the manifest.json without user (my setup has username/password set) response is 401.

````
10.0.0.102 - - [18/Nov/2024:18:44:06 +0200] "GET /cloudcmd/static/manifest.json HTTP/1.1" 401
````

When requesting the the url after everything is loaded we get res

````
10.0.0.201 - hagay [18/Nov/2024:18:45:12 +0200] "GET /cloudcmd/static/manifest.json 200
````

It seems manifest.json needs to be somehow freely accessible even cloudcmd has authentication enabled. (Tested on dev setup which not had authentication setup)

**Comment by coderaiser** [comment]
Are you up for a PR?

**Comment by hagaygo** [comment]
For now , as a workaround, I disabled the auth on cloudcmd , refreshed the page and it allowed me to add it as PWA, then i restored the auth setting on cloudcmd

> Are you up for a PR?
We need to put the manifest.json on a folder that does not require authentication , even if one is set on cloudcmd.
If there isn't one , we need to define it via nodejs somehow (not familiar with it).
I can try to look into , but if you know of such folder or how to setup one , its quite easy/fast to do.

**Comment by coderaiser** [comment]
Good idea! Here is the code:
https://github.com/coderaiser/cloudcmd/blob/03e3ba6ad8a067ea3985164a5b8ff313b73c13d8/server/auth.js#L17

how we call this directory?

**Comment by hagaygo** [comment]
I think "public" is a good name for this kind of folder.

**Comment by coderaiser** [comment]
Yea it’s good, the only thing would be great to add test, so we do not remove this feature accidentally in future

**Pull request merged**
