### PR TITLE
feature(docker) multi-arch: resolve issues with multi-arch docker images

### PR DESCRIPTION
**Pull request by timoknapp**
- [x] commit message named according to [Contributing Guide](https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md "Contributting Guide")
- [x] `npm run codestyle` is OK
- [x] `npm test` is OK

Hi @coderaiser ,

as discussed, this is the PR fixing the issue #291 . I removed the old way of building the `docker` images using `travis` and `madrun`. We will now make use of GitHub actions.

**HINT:** Please make sure to add the required Secrets within your repository settings, otherwise the action wont run properly and wont be able to push the images to `docker hub`. I also added a `TODO:` for you inside the `.github/workflows/docker.yml:37`[here](https://github.com/timoknapp/cloudcmd/blob/master/.github/workflows/docker.yml#L41:L42)

In case you want to have a look how thing will then look like. Here is a link to [my action](https://github.com/timoknapp/cloudcmd/runs/1723918069) from my fork. And here are the related [images](https://hub.docker.com/r/team0/cloudcmd/tags?page=1&ordering=last_updated) from dockerhub.

Let me know if those changes suit your expectations.
Regards

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d09a73e5e6b252d44d3480d5e699e7e9519e2972
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**
  * Invalid type. Valid types are **fix, docs, refactor, test, chore, feature**

 * Commit: 6b51bcfcfc1d08105bf5b06acf810c7b7200f0f9
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

 * Commit: b55ad0cfcfb1f310f252eab5d4a2b5013e3507be
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**

 * Commit: 182c9aac135faf954deb0623f2e40b6c4e7f5ed7
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**
  * Invalid type. Valid types are **fix, docs, refactor, test, chore, feature**

 * Commit: ffa402570ff2addfd1d73d12aec99f152da0c9ce
  * Commits must be in the following format: **%{type}(%{scope}) %{description}**
  * Invalid type. Valid types are **fix, docs, refactor, test, chore, feature**

 * Commit: b4f44d4629aff1ae696f1e5e3af5b29b87eab2bb
  * Invalid type. Valid types are **fix, docs, refactor, test, chore, feature**

Guidelines are available at https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by timoknapp** [comment]
Just noticed the issues regarding the commit history. Can we just squash the commits with the PR?

**Comment by coderaiser** [comment]
Nice, it's looks much simpler :). Thanks a lot 🎉

**Comment by timoknapp** [comment]
You're welcome :)

**Comment by timoknapp** [comment]
@coderaiser 

Just noticed, the Workflow is now failing. It seems that you did not yet provide the credentials to docker hub yet?

`DOCKER_USERNAME` must be your username whereas `DOCKER_PASSWORD` shall be an API-Token created for you account. You can generate that one on the account settings within docker hub. Afterwords you need to set the variables as secrets within your repository settings.
In case you need further assistance, just ping me.

Whenever the workflow runs smoothly, we can also close #291 :)

**Comment by coderaiser** [comment]
Just set credentials :), could you please check if it is works https://github.com/coderaiser/cloudcmd/runs/1727448787?check_suite_focus=true.

Also I want to to run docker builds only for tags, I think [this should be fine](https://github.com/coderaiser/cloudcmd/blob/master/.github/workflows/docker.yml#L3-L6), as I see from [here](https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/23).

**Comment by timoknapp** [comment]
Looks good now, at least the base images get build a published correctly:

https://hub.docker.com/r/coderaiser/cloudcmd/tags?page=1&ordering=last_updated

But the alpine images wont be pushed to the same images as the base ones:

https://hub.docker.com/r/coderaiser/cloudcmd-alpine/tags?page=1&ordering=last_updated

So that part needs to be changes within the `docker.yml`. I will fix it and create a new PR during the day. 
With regards to running the docker builds on tags only, your configuration looks correct. :)

**Pull request merged**
