### PR TITLE
fix(authentication) auth failure (??)

### PR DESCRIPTION
**Pull request by ShRyDeR**
???
without doing this, auth wouldnt work

its weird that such big project has this bug, or is it even a bug? no idea but this fix made auth work for me ._.

### CODE REVIEW

**Comment by ShRyDeR** [comment]
my first pull request

**Comment by coderaiser** [comment]
`~/.cloudcmd.json` contains [password hash](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/json/config.json#L5) because of security reason, if someone steal your config, he wouldn't know your password, because hash is [very strong](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/json/config.json#L6) and can be customized.

You should never write your password as plain text to `~/.cloudcmd.json`, you can generate password using `cloudcmd` itself:

```
cloudcmd --username your_user --password your-password --auth --save --no-server
```

This command will create hash of your password and write it to `~/.cloudcmd.json`.

Thank you for attention to details 👍, if you want you can add this example to [documentation](https://github.com/coderaiser/cloudcmd/blob/master/HELP.md#authorization), it will be very useful 🙂.

**Comment by coderaiser** [comment]
Related to #72, #147.

**Comment by ShRyDeR** [comment]
Ah i see, thank you!

**Pull request closed without merging**
