### PR TITLE
fix(docker) images: change alpine images to be part of master image (#291)

### PR DESCRIPTION
**Pull request by timoknapp**
- [x] commit message named according to [Contributing Guide](https://github.com/coderaiser/cloudcmd/blob/master/CONTRIBUTING.md "Contributting Guide")
- [x] `npm run codestyle` is OK
- [x] `npm test` is OK

Hotfix to move the alpine images to be part of the master images :)

### CODE REVIEW

**Comment by timoknapp** [comment]
@coderaiser 
Whenever this PR is merged you can remove the following images within docker hub, as the new alpine images will be published within the main image :)

https://hub.docker.com/r/coderaiser/cloudcmd-alpine/tags?page=1&ordering=last_updated

**Comment by coderaiser** [comment]
Nice :), thank you.

**Comment by timoknapp** [comment]
Your welcome 👍

**Comment by coderaiser** [comment]
Landed in [v15.3.4](https://github.com/coderaiser/cloudcmd/releases/tag/v15.3.4) 🎉 . 

Could you please take a look how it's going https://github.com/coderaiser/cloudcmd/runs/1728970564?check_suite_focus=true

**Comment by timoknapp** [comment]
@coderaiser  Thanks for merging. It all looks really nice. Workflow ran smoothly

[Here](https://hub.docker.com/r/coderaiser/cloudcmd/tags?page=1&ordering=last_updated) are the most recent images from docker hub.

**Pull request merged**
