### PR TITLE
fix: cloudcmd: Make manifest.json accessable when authentication is enabled

### PR DESCRIPTION
**Pull request by hagaygo**
When authentication is enabled manifest.json needs to be available without authentication since mobile browser requests it without credentials.

More info on https://github.com/coderaiser/cloudcmd/pull/426

### CODE REVIEW

**Comment by coderaiser** [comment]
Nice! Could you please add test similar to this one:

https://github.com/coderaiser/cloudcmd/blob/03e3ba6ad8a067ea3985164a5b8ff313b73c13d8/server/cloudcmd.spec.mjs#L140

And would be great to move out one dat all auth-related tests to `auth.spec.js`

**Comment by hagaygo** [comment]
> Nice! Could you please add test similar to this one:
> 
> https://github.com/coderaiser/cloudcmd/blob/03e3ba6ad8a067ea3985164a5b8ff313b73c13d8/server/cloudcmd.spec.mjs#L140
> 
> To check that behaviour you implemented works as expected: no auth for `/public/manifest.json`.
> 
> And would be great to move out one day all auth-related tests to `auth.spec.js`

Hi , just looked at the test code.

As far i can understand the current tests check only if the username & password match if auth is enabled , no options to check request/url.
Since the exclude path logic of public folder is not handled under _initAuth function we either need other/new test infrastructue that allows us the test the _middle function or somehow move it the code change from _middle function to _initAuth function (which seems wrong/not possible)

**Comment by coderaiser** [comment]
Yes, you right it is wrong test, here is what we need:

https://github.com/coderaiser/cloudcmd/blob/03e3ba6ad8a067ea3985164a5b8ff313b73c13d8/server/cloudcmd.spec.mjs#L175

**Comment by hagaygo** [comment]
added a test now , verified that without my previous commit the test fails.

**Comment by coderaiser** [comment]
Thank you! Landed in [v18.4.0](https://github.com/coderaiser/cloudcmd/releases/tag/v18.4.0) 🎉

**Pull request merged**
